Traceback (most recent call last):
  File "/application/src/tg_bot/handlers/user_private.py", line 343, in get_faq_answer
    await callback.message.answer(faq_question)
  File "/usr/local/lib/python3.10/site-packages/aiogram/types/message.py", line 2091, in answer
    return SendMessage(
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=<src.database.models.FAQ object at 0x7f42262fadd0>, input_type=FAQ]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
